version: "3"
services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql:mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: reflets
      PMA_HOST: mysql

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis:/data
